- lib/key_master.rb
I added method `description` and `debugQuickLookObject`.
Because it is for ease of debugging.
```Objective-C
MyApplicationKeys *keys = [[MyApplicationKeys alloc] init];
NSLog(@"%@", keys);
```
```
2015-01-13 19:30:13.473 CocoapodKeysDemo[73971:3095487] {
NetworkAPIToken = AH2ZMiraGQbyUd9GkNTNfWEdxlwXcmHciEOH;
AnalyticsToken = 6TYKGVCn7sBSBFpwfSUCclzDoSBtEXw7;
}
```
QuickLook
> Adds method for debug

- lib/key_master.rb
The `data` and `static char <%= name %>Data[<%= @data_length %>]` are the same length.
But the interpretation of length will change by the escape sequence.
So I was supported by adding fixed double-quote.
If you have nice idea, close the PR.
> Fail build if the double-quote contains in the value

- lib/plugin.rb
Related to https://github.com/orta/cocoapods-keys/pull/31#commitcomment-9562540
This removes the inclusion of modules into the monkey-patched core classes and thus ensuring less chance for collisions.
(This is completely untested code btw, please test it on your existing test project.)
> @ashfurrow => Less namespace pollution

- lib/preinstaller.rb
Sets `@user_options` to a local variable and verifies the keys before accessing it.
This was my attempt to fix #39.
My ruby is a bit rusty, though :)
> Uses a default value for user_options

- lib/key_master.rb
- lib/plugin.rb
- lib/preinstaller.rb
Addresses the crashes that happens when there is no "plugin 'cocoapods-keys'" present in the Podfile.
More specifically, the backtrace I was getting was:
```
NoMethodError - undefined method `[]' for nil:NilClass
/Users/dbarden/.gem/ruby/2.1.2/gems/cocoapods-keys-1.0.1/lib/plugin.rb:6:in `podspec_for_current_project'
/Users/dbarden/.gem/ruby/2.1.2/gems/cocoapods-keys-1.0.1/lib/plugin.rb:66:in `from_string'
/Users/dbarden/.gem/ruby/2.1.2/gems/cocoapods-core-0.36.0/lib/cocoapods-core/specification.rb:536:in `from_file'
/Users/dbarden/.gem/ruby/2.1.2/gems/cocoapods-0.36.0/lib/cocoapods/sandbox.rb:212:in `block in specification'
/Users/dbarden/.gem/ruby/2.1.2/gems/cocoapods-0.36.0/lib/cocoapods/sandbox.rb:212:in `chdir'
/Users/dbarden/.gem/ruby/2.1.2/gems/cocoapods-0.36.0/lib/cocoapods/sandbox …
```
> Support for empty plugin section

- lib/preinstaller.rb
There were two problems causing the issue. First, during `PreInstaller` initialization, we were assigning to an instance variable that was never read from, due to a problem in [this commit](https://github.com/orta/cocoapods-keys/commit/a0af25643c00687149708095b21a7f59cdd2dbe7#diff-94f3f33afc788f0a2a651f67e55ef6c6R12). In a separate, but related [commit](https://github.com/orta/cocoapods-keys/commit/4ad5a07f2b86534f0746910bf05ebd5cdcce12f9#diff-94f3f33afc788f0a2a651f67e55ef6c6R17), we changed a local variable's setup to use the `project` variable instead of the (now deleted) `name` variable, but still used `name` later on.
As @orta [mentioned](https://github.com/orta/cocoapods-keys/pull/41#issuecomment-78383660), we're getting to the size that a test suite is going to help catch these …
> @orta => Fixes problems with non-defined keys

- .travis.yml
- spec/key_master_spec.rb
- templates/Keys.m.erb
These were causing incorrect termination of the C-string literal.
Fixes #33.
The tests aren’t the nicest and I’d have preferred to not do the payload sanitation in the ERB template, but it works and it looks like @lyricsboy is already working on cleaning that up, so I’ll wait for that first. https://github.com/orta/cocoapods-keys/issues/46
> Escape backslashes and double-quotes in payload.

- lib/name_whisperer.rb
Without it, this question lacks any context about what Xcode project something wants to know about:
```
$ pod install
Hello there, we found too many xcodeprojects. Please give a name for this project.
>
```
> Include plugin name in UI when asking a question.

- lib/plugin.rb
- lib/preinstaller.rb
This ensures that:
* it doesn’t matter if the user uses Symbol or String keys in their Podfile
* the plugin never tries to auto-detect the Xcode project (and possibly ask the user questions) if the user specifies the Xcode project
> Fix option fetching

- templates/Keys.m.erb
It was probably double-escaped because the template was first inside a Ruby source file, but since it’s in an external file this double-escape breaks the proper building of a string.
> [Template] Fix double-escape of string NULL termination.

- lib/plugin.rb
Installing with a custom project directory:
```bash
$ bundle exec pod install --project-directory=src
mkdir: Pods: No such file or directory
cp: Pods/CocoaPodsKeys: No such file or directory
... snip ...
Errno::ENOENT - No such file or directory @ rb_sysopen - Pods/CocoaPodsKeys/MUDRammerKeys.h
/Users/jh/Dev/cocoapods-keys/lib/plugin.rb:27:in `write'
/Users/jh/Dev/cocoapods-keys/lib/plugin.rb:27:in `setup'
/Users/jh/Dev/cocoapods-keys/lib/plugin.rb:72:in `install!'
/Users/jh/Dev/MUDRammer/vendor/bundle/ruby/2.2.0/gems/cocoapods-0.37.1/lib/cocoapods/command/project.rb:71:in `run_install_with_update'
/Users/jh/Dev/MUDRammer/vendor/bundle/ruby/2.2.0/gems/cocoapods-0.37.1/lib/cocoapods/command/project.rb:101:in `run'
/Users/jh/Dev/MUDRammer/vendor/bundle/ruby/2.2.0/gems/claide-0.8.1/lib/claide …
```
> Install to path specified by project directory

- CHANGELOG.md
- lib/plugin.rb
Basically we're now being suuuper cautious about validating, and fail via shortcircuiting if anything goes wrong. 
Fixes #63.
Fixes #55.
> @orta => Adds support for linting pods with cocoapods-keys installed on system.

- README.md
- SWIFT_PROJECTS.md
I've written some documentation to use `cocoa pods-keys` in Swift projects since I ran into some issues last night. Nothing @ashfurrow and the proper name of the module to import couldn't fix.
I saw in #65 that you preferred having this documentation in a separate file so here it is. Please let me know if the name of the file, the way it's introduced in the README and the content isn't good or clear enough.
I guess a "Troubleshooting" section would be nice as well but since I didn't encounter any major issues I wasn't sure what to write.
> Adding some documentation for swift project

- lib/preinstaller.rb
This commit renames `UI` to `ui`. Should fix https://github.com/orta/cocoapods-keys/issues/81.
> This should fix the uninitialized constant reported in #81

- lib/plugin.rb
This fixes an issue introduced by #93.
A project that has its `Podfile` and other files in a `src` directory has its keys files placed improperly at `Pods/CocoaPodsKeys`, from the root of the repo, when they should be placed at `src/Pods/CocoaPodsKeys`.
Thanks to @segiddins for the fix!
> [Paths] Fixed relative paths from installation roots

- lib/key_master.rb
- lib/name_whisperer.rb
- lib/pod/command/keys.rb
Additional fixes for project files that do not live in the root of the repo.
In particular:
- This syntax should now be allowed (and preferred?): `bundle exec pod keys --project-directory=src set [KEY] [VALUE]`
- Fixes an exception:
```bash
NoMethodError - undefined method `basename' for "Mudrammer.xcodeproj":String
/Users/distiller/MUDRammer/vendor/bundle/ruby/2.0.0/gems/cocoapods-keys-1.3.1/lib/name_whisperer.rb:11:in `get_project_name'
/Users/distiller/MUDRammer/vendor/bundle/ruby/2.0.0/gems/cocoapods-keys-1.3.1/lib/pod/command/keys/set.rb:55:in `current_keyring'
/Users/distiller/MUDRammer/vendor/bundle/ruby/2.0.0/gems/cocoapods-keys-1.3.1/lib/pod/command/keys/set.rb:41:in `run'
/Users/distiller/MUDRammer/vendor/bundle/ruby/2.0.0/gems/claide-0.8.1/lib/claide/command.rb:312:in `run' …
```
> [Paths] Additional project keys paths fixes

- lib/keyring.rb
- lib/keyring_liberator.rb
- lib/name_whisperer.rb
- lib/plugin.rb
- lib/pod/command/keys.rb
- lib/pod/command/keys/get.rb
- lib/pod/command/keys/rm.rb
- lib/pod/command/keys/set.rb
- lib/preinstaller.rb
- spec/functional_spec.rb
- spec/keyring_liberator_spec.rb
- spec/keyring_spec.rb
I was keeping two copies of my project around so that I could verify bugs in a separate Xcode window than the one where I'm working on a new feature (obv a separate branch would do the same, but would require full recompiles, which takes 2-3 days when compiling Swift files).
I added a key to the "main" project, and kept getting the error "CocoaPods-Keys has detected a keys mismatch for your setup."  Looking into it, it was because `get_keyring_named` was returning the wrong Keyring.
So here are two ideas: one, check the path.  Brittle if the user renames their project folder.  Two, emit a warning (error?) if two keyrings have the same name.
Both of these dodge the issue of what to DO when two projects have the same name!  In the actual keychain entries will be shared between the two …
> [WIP] Some thoughts around projects that have the same name.

- Gemfile.lock
- README.md
- cocoapods_keys.gemspec
- lib/preinstaller.rb
Fixes #105
With this PR you could create a `.env` file in your project folder for all secret files.
So it's easier to share credentials in the team.
> Add support for loading environment `.env` file

- CHANGELOG.md
- lib/pod/command/keys.rb
- lib/pod/command/keys/export.rb
- spec/functional_spec.rb
Usage is documented; it works like this:
```
> pod keys export
pod keys set ArtsyAPIClientSecret - Eidolon
pod keys set ArtsyAPIClientKey - Eidolon
pod keys set HockeyProductionSecret - Eidolon
pod keys set HockeyBetaSecret - Eidolon
pod keys set MixpanelProductionAPIClientKey - Eidolon
pod keys set MixpanelStagingAPIClientKey - Eidolon
pod keys set CardflightStagingAPIClientKey - Eidolon
pod keys set CardflightStagingMerchantAccountToken - Eidolon
pod keys set StripeStagingPublishableKey - Eidolon
pod keys set CardflightProductionAPIClientKey - Eidolon
pod keys set CardflightProductionMerchantAccountToken - Eidolon
pod keys set StripeProductionPublishableKey - Eidolon
```
Where the `-` is actually the real key (they're all OSS keys in this example). Now we can copy+paste this output into …
> Adds export command.

- README.md
- lib/pod/command/keys/rm.rb
If Wildcards are included, it will remove the keys matching the pattern. E.g.: `pod keys rm "G*og*"` will remove *all* the keys that begin with 'G', have 'og' in the middle and end with anything.  
To nuke all the keys, run either `pod keys rm "*"` or `pod keys rm --all`.  
It should close #111. /cc @ashfurrow
> Adding the option to remove multiple keys at once by using wildcard

- lib/preinstaller.rb
For example, if a key is removed from the Podfile, then running `pod install` results in the removed key still being present in the yml file, and thus still getting added to the generated *.h/m files.
> Keys that have been removed from the project weren't being deleted from the YML file.

- lib/key_master.rb
Fixes #113 by ensuring the `keys_length` doesn't return nil.
> Fixes undefined method '*' for nil:NilClass issue on first run

- SWIFT_PROJECTS.md
The usage link to the readme ended up being a 404. Not entirely sure if this is the best way to write relative links on Github, but it works :/
> Fixed usage link

- SWIFT_PROJECTS.md
I was just about to open a new issue 
> i have an existing project setup with cocoapods-keys and the relevant swift file imports `Keys` just fine with all of the initial keys (setup through the interactive configuration from the first `pod install`) are there, but a new key added later on is not found.
> i took a peek, and the generated `*h/*m` files include the new key, as well as a `pod keys` output -- but the generated swift `public class SuperSpecialSecretKeys : NSObject { ...` class is missing it.
> cocoapods version 1.0.1
when I thought to clear out Xcode's derived data folder––problem solved. I don't quickly think to clear that finder folder, not sure if others do when strangeness happens, but updated the swift-related docs to include this situation for future instances.
> Enhance Swift usage docs

- CHANGELOG.md
- lib/preinstaller.rb
I frequently see new projects on CI that will timeout waiting for user input when missing key env vars.
It probably makes sense to do this in other places that ask for user input too?
> Raise when asking for keys on CI

- templates/Keys.h.erb
- templates/Keys.m.erb
`@dynamic` in .h file added to prevent Objective C generating default ivar and a getter which ruins runtime magic in `resolveInstanceMethod`.
> Converted key methods to properties 

- lib/pod/command/keys/generate.rb
The parameter was listed in the README but not implemented.
This PR should allow the generation of key files without user intervention on projects with multiple Xcode projects files.
> Add missing 'project_name' param to generate command

- templates/Keys.podspec.json
This fixes #180 by adding the missing platforms with proper minimal requirements.
Cocoapods-Keys does not use any API introduced after iOS 2.0, but requires ARC (introduced
in 5.0). It does not, as far as I'm aware, require iOS 8.0. So this should also fix broken
builds for apps targeting iOS 5, 6 and 7.
WatchOS 8.3 does not exist. The current version is 4.3, although this plugin is compatible
with 2.0.
TvOS 8.3 also never existed. The original version was 9.0.
For OS X/macOS, there is no dependency on Yosemite (10.10). ARC was introduced in Lion
(10.7).
**Note:** This PR does _not_ address #182, as sanitizing the tests will require more
work.
> 🐛 Fixes #180 and add other missing platforms

- lib/keyring_liberator.rb
I noticed some timeouts in Jenkins with the following format:
```
[15:37:12]: $ bundle exec pod install
[15:43:17]: ▸ About to create a duplicate keyring file for project REDACTED
[15:43:17]: ▸ Entries in your Apple Keychain will be shared between both projects.
[15:43:17]: ▸ Press enter to continue, or `ctrl + c` to cancel
```
The script is waiting for input, but since we’re on CI that isn't practical. I found this message in the project in `keyring_liberator.rb` and noticed that the list of environment variables it uses to determine if it's running in CI is different than in `preinstaller.rb`, so I copied the latter's list into the former.
I'm not super great with Ruby, so I didn't attempt to make both files pull this method from the same source file, but that would be the obvious …
> Fix for duplicate keyrings in Jenkins

- lib/pod/command/keys/set.rb
As of now, every time a new key is set, it gets appended to the list of keys on the yaml file and if it already exists for that keyring, it will get duplicated. I can't think of any serious consequences that this may cause, but after a while the yaml file becomes messy and the output of `pod keys` too. In other words, this is just 💅, but hopefully you guys like it. 🙂
> Store only unique keys in the keyring

- CHANGELOG.md
- lib/pod/command/keys/generate.rb
When running in CI, we've opted to just run the `pod keys generate` command rather than `pod install` to generate the obfuscated objc files. However, as we're using ENV keys to set the values there aren't any keyring yaml files that contains the name of the keys and as such the command doesn't know the name of the ENV variables to look for.
Add an option `--keys` to the generate command that's used to create a runtime keyring if no existing keyring could be found, letting the system know which keys to look for.
```
export Foo=foo
export Bar=bar
pod keys generate --keys=Foo,Bar
```
> Add fallback keys option to generate command

- lib/key_master.rb
- templates/Keys.m.erb
I've tested this with Artsy's codebase to make sure it still works 👍 It puts the data in an NSString, and uses `characterAtIndex:` Objective-C function calls, which are unlikely to be inlined by the compile. This might incur some performance penalty, but, that's probably fine.
I also made some refactors to use less Objective-C runtime stuff and make this easier to maintain. The downside of this approach is that it loads _all_ keys upfront in `init`, which has potential further performance impacts. This now optimizes for creating fewer instances of the `Keys` object, since creating each one is more expensive but each key access is free. 
The refactor is in a separate commit in case you'd like to keep the original implementation. I have verified both commits solve the problem of inlining …
> Fix C inlining issues

- .gitignore
- Gemfile.lock
- README.md
This is mostly just running `bundle install` to update the `Gemfile.lock` file ([example failing build](https://travis-ci.org/github/orta/cocoapods-keys/builds/704808391)). Also did some cleanup.
This is trivial, so I'm going to self-assign.
> Fixes CI #trivial

- lib/key_master.rb
Fix #229 
I fixed these two warnings
- `Passing safe_level with the 2nd argument of ERB.new is deprecated. Do not use it, and specify other arguments as keyword arguments.`
- `Passing trim_mode with the 3rd argument of ERB.new is deprecated. Use keyword argument like ERB.new(str, trim_mode: ...) instead.`
> Use keyword argument like ERB.new(str, trim_mode: ...) instead
